version: "3.8"
services:
  postgres:
    container_name: db
    image: "postgres:15"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
      POSTGRES_HOST: localhost
    networks:
      - local
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: "dpage/pgadmin4:5.7"
    environment:
      PGADMIN_DEFAULT_EMAIL: example@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - local

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.2
    command:
      - start-dev
    depends_on:
      - "postgres"
    environment:
      KC_DB: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: postgres
      KC_HEALTH_ENABLED: true
      KC_HTTP_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080 # If you wanna change port
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
      - "8787:8787" # debug port
    networks:
      - local

networks:
  local:
    name: local
    driver: bridge

volumes:
  postgres_data: